name: CI/CD Full Stack

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 4. Build backend and frontend images
      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/motobackend:latest ./Backend/MotoRide

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/motofrontend:latest ./Frontend

      # 5. Push images to Docker Hub
      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/motobackend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/motofrontend:latest

      # 6. Deploy to remote server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
           rm -rf ~/fullstack
           git clone https://github.com/Leen11002/FULLSTACK.git ~/fullstack
           cd ~/fullstack
           docker compose up -d --build --remove-orphans
